name: Java CI with IntelliJ

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with IntelliJ
      run: |
        # Exécuter les commandes pour construire votre projet avec IntelliJ
        # Par exemple :
        # ./gradlew build ou ./mvnw package ou toute autre commande spécifique à votre projet
    - name: Run tests
      run: |
        # Exécuter les commandes pour exécuter les tests de votre projet
        # Par exemple :
        # ./gradlew test ou ./mvnw test ou toute autre commande spécifique à votre projet
      continue-on-error: true
    - name: Check test results
      if: ${{ failure() }}
      run: echo "Tests failed!"
    - name: Create failure branch
      if: ${{ failure() }}
      run: |
        # Créer une nouvelle branche en cas d'échec des tests
        # Remplacez les commandes ci-dessous par les commandes spécifiques à votre dépôt
        git checkout -b failure-branch
        git add .
        git commit -m "Test failure"
        git push origin failure-branch
    - name: Git reset
      run: git reset --hard HEAD@{1}
    - name: Fast forward
      run: git pull --ff-only
