name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn test
      continue-on-error: true
    - name: Check test results
      if: ${{ failure() }}
      run: echo "Tests failed!"
    - name: Create failure branch
      if: ${{ failure() }}
      run: git checkout -b failure-branch && git add . && git commit -m "Test failure" && git push origin failure-branch
    - name: Git reset
      run: git reset --hard HEAD@{1}
    - name: Fast forward
      run: git pull --ff-only

